### ISSUE TITLE
Add option to run on single machine

### ISSUE THREAD

**Issue by truongnmt** [phuonglh/vn.vitk#13]
Can you make an argument to run on single machine, cause it required data on /export/dat/* 
So I have to change code on every "/export" to this repo path.
An argument or a config data path is much easier.

**Comment by phuonglh** [comment]
Hi. I do not really understand your question. If you want to run on a single machine, all you need to do is to create the data folder /export/dat/ on that machine. Why do you have to change code?

Btw, I will include all the required data as resources, which will be packed into a single JAR file in the next version.

**Comment by laynelee28** [comment]
hi, you said “ you need to do is to create the data folder /export/dat/ on that machine”，but，where should I create the file, under the C: disk or somewhere? can you give me more details?

**Comment by phuonglh** [comment]
Hi. In a Unix/Linux/MacOS system, / is the root directory. 

If you are on a Windows machine, it depends on particular system. I think that's something C:/, D:/ or something like that, but I'm not sure because I have not used any Windows system for many years. Please check yourself what is your root folder.
